from fastapi import APIRouter, Depends, UploadFile, File
from sqlalchemy.orm import Session
from app.database import SessionLocal
from app.models.company import Company
from app.schemas.company import CompanyCreate

router = APIRouter(prefix="/admin/company", tags=["Admin - Company"])

def get_db(): #this function is used to get the database session which will be used in the routes to interact with the database
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@router.post("/") #admin can add a company by providing the necessary details in the request body
def add_company(data: CompanyCreate, db: Session = Depends(get_db)): #data is used to get the data from the request body and db is used to interact with the database, we are using the get_db function to get the database session and Depends is used to inject the dependency of the database session in the route
    company = Company(**data.dict()) #we are creating an instance of the Company class and passing the data from the request body to the constructor of the Company class, **data.dict() is used to unpack the data from the request body and pass it as keyword arguments to the constructor of the Company class
    db.add(company) #we are adding the company instance to the database session, this will not actually add the record to the database until we commit the session
    db.commit() #we are committing the session to actually add the record to the database
    db.refresh(company) #we are refreshing the company instance to get the updated data from the database, this is necessary because after committing the session, the company instance will not have the id which is generated by the database, so we need to refresh the instance to get the id and other details from the database
    return company

@router.get("/") #user can view all the companies which are added by the admin
def view_companies(db: Session = Depends(get_db)):
    return db.query(Company).all()

@router.get("/names")
def get_company_names(db: Session = Depends(get_db)):
    companies = db.query(Company.name).all()
    return [company[0] for company in companies]


@router.get("/{company_name}")
def search_company_by_name(company_name: str, db: Session = Depends(get_db)):
    company=  db.query(Company).filter(Company.name.ilike(f"%{company_name}%")).all() #ilike is used to perform case-insensitive search in the database, % is used as a wildcard character to match any sequence of characters before and after the company name which is passed in the request body
    if not company:
        return {"error": "Company not found"}
    return company



@router.put("/{company_id}") #admin can update the company details by providing the company id in the path parameter and the new details in the request body
def update_company(company_id: int, data: CompanyCreate, db: Session = Depends(get_db)): #session is used to interact with the database, we are using the get_db function to get the database session and Depends is used to inject the dependency of the database session in the route
    company = db.query(Company).filter(Company.id == company_id).first() #first() is used to get the first record which matches the condition, in this case we are matching the company id with the company_id which is passed in the request body
    #.filter() is used to filter the records based on the condition provided in the parentheses, in this case we are filtering the records based on the company id which is passed in the request body
    if not company:
        return {"error": "Company not found"}
    for key, value in data.dict().items(): #we are iterating through the data from the request body and updating the company instance with the new data, data.dict() is used to convert the Pydantic model to a dictionary, items() is used to get the key-value pairs from the dictionary, we are using setattr() to set the attributes of the company instance with the new values from the request body
        setattr(company, key, value) #setattr() is a built-in function in Python which is used to set the value of an attribute of an object, it takes three arguments, the first argument is the object, the second argument is the name of the attribute as a string, and the third argument is the value to be set for that attribute
    db.commit()
    db.refresh(company)
    return company

